# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  versionToBuild: ''
  

name: $(BuildID)

steps:
- checkout: self
  submodules: true

- script: |
    set /p VER=<src/version.txt
    @echo ##vso[task.setvariable variable=versionToBuild]%VER%

- script: |
    echo The version from src/version.txt is $(versionToBuild)
    @echo ##vso[build.updatebuildnumber]$(versionToBuild).$(build.buildnumber)

- task: NuGetToolInstaller@0
  inputs:
    versionSpec: '5.8.x'

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 3.1.402'
  inputs:
    packageType: sdk
    version: 3.1.402
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'src/MDD4All.SVG.sln'
    arguments: '-c $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Pack SVG generator'
  inputs:
    command: 'pack'
    packDirectory: '$(Build.ArtifactStagingDirectory)'
    packagesToPack: 'src/MDD4All.SVG.sln'
    nobuild: true
    arguments: '-c $(buildConfiguration)' 
    versioningScheme: byEnvVar
    versionEnvVar: build.buildnumber
    verbosityPack: 'normal'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'src/MDD4All.SVG.EAFacade.sln'
    arguments: '-c $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Pack SVG generator (Facade)'
  inputs:
    command: 'pack'
    packDirectory: '$(Build.ArtifactStagingDirectory)'
    packagesToPack: 'src/MDD4All.SVG.EAFacade.sln'
    nobuild: true
    arguments: '-c $(buildConfiguration)' 
    versioningScheme: byEnvVar
    versionEnvVar: build.buildnumber
    verbosityPack: 'normal'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: Output
